### ISSUE TITLE
Crash when used in an SSH Mount

### ISSUE THREAD

**Issue by JDougherty** [mate-desktop-legacy-archive/mate-file-manager-open-terminal#1]
Attempting to open a terminal from the context menu within Caja when the current directory is in a SSH mount causes Caja to crash (and the terminal does not open).

To Reproduce:
1) Open Caja
2) Click `File` menu, choose `Connect to Server` 
3) Choose service type `SSH` and fill  in some details for a server 
4) Once mounted, browse the SSH mount
5) Right Click and choose `Open In Terminal`

**Comment by ParisLiakos** [comment]
I am able to reproduce it in debian.
this is definitely a bug

**Comment by sbalneav** [comment]
Fixed in commit 7ba0ea3dc0f257a57a6ec30f337df6731bd0c57b
