### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by Jojo144** [mate-desktop-legacy-archive/mate-file-manager-open-terminal#10]
Should it be possible to bind the action "open in terminal" to the key F4?
(Like in Lubuntu, it is very handy !)
What do you think of this ?

Thanks.

**Comment by monsta** [comment]
Please don't post issues in obsolete repos.
This one should go into https://github.com/mate-desktop/caja-extensions/issues

**Comment by Jojo144** [comment]
Ooops. Excuse me.
Reposted there: https://github.com/mate-desktop/caja-extensions/issues/16

**Comment by monsta** [comment]
No problem. You can close this one now.
