### ISSUE TITLE
Support opening remote terminal

### ISSUE THREAD

**Issue by JDougherty** [mate-desktop-legacy-archive/mate-file-manager-open-terminal#2]
For some reason I don't see this feature in Caja. When in a mounted SSH/SFTP directory, there is no option to open a remote terminal. This feature is a part of the original gnome2 nautilus-open-terminal (http://git.gnome.org/browse/nautilus-open-terminal/) so I am not sure why it has not been included in this project.

**Comment by sbalneav** [comment]
Fixed in commit 7ba0ea3dc0f257a57a6ec30f337df6731bd0c57b
