### ISSUE TITLE
crash when opening network drive in terminal

### ISSUE THREAD

**Issue by acscd** [mate-desktop-legacy-archive/mate-file-manager-open-terminal#8]
I'm not sure whether to report this here or under mate-file-manager, but I'll try here.

Whenever I have a network drive mounted and I right click on or in it and select open in terminal, caja crashes. I'm using MATE 1.6.1, on Sabayon x86_64.

**Comment by raveit65** [comment]
Can you open a terminal in 'sftp://localhost/' for confirming?
This crashed in my fedora box too.

**Comment by stefano-k** [comment]
@NiceandGently do you have a backtrace?

**Comment by raveit65** [comment]
@stefano-k 
I think this is the same issue. backtrace (fedora report) and possible solution.
https://github.com/mate-desktop/mate-file-manager-open-terminal/issues/9

**Comment by stefano-k** [comment]
Duplicate of #9
